server:
  port: 8101
spring:
  application:
    name: iplume-fi-auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iplume_fi?autoReconnect=true
    username: root
    password: Aa123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

# eureka config.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

# 暴露规则.
management:
  endpoints:
    web:
      exposure:
        include: "*"
# jwt.
jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: iplume-fi-auth-security

aes:
  encrypt_key: iplume_key_12345
